---
# tasks file for letsencrypt
- name: "install letsencrypt"
  apt:  name=letsencrypt

- name: "set paths to private key and certificate"
  set_fact:
    tls_privete_key_path: "/etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}/privkey.pem"
    tls_certificate_path: "/etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}/fullchain.pem"

- name: "check letsencrypt cert already retrived"
  stat:
    path: "/etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}"
  register: stat_result

- name: "ensure webroot directory exists"
  file:
    path:  "{{ letsencrypt_webroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode:  0775

- name: "create temporary nginx server to accept letsencrypt http request"
  include_tasks: nginx_site.yml
  when: stat_result.stat.exists == False

- name: "retreive certificate"
  shell: "letsencrypt certonly -n --agree-tos --email {{ letsencrypt_hostmaster }} -a webroot --webroot-path={{ letsencrypt_webroot }} -d {{ letsencrypt_domain_names|join(' -d ') }}"
  when: stat_result.stat.exists == False

- name: "clean temporary nginx server"
  include_tasks: nginx_site_cleanup.yml
  when: stat_result.stat.exists == False

- name: "configure nginx ssl"
  include_tasks: nginx_ssl.yml

- name: "setup cron job for certificate update"
  cron:
    name:   "letsencrypt/certificate update"
    minute: "0"
    hour:   "8"
    day:    "21"
    job:    "/usr/bin/letsencrypt renew  >> /var/log/letsencrypt.renew.log; service nginx restart"
