---
# gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
# aaheiev/mc-iac:0.0.1-1
secrets:
  gcloud_sa_key.json:
    file: .secrets/aaheiev-335511-6d43ea04da41.json
services:
  iac:
    image:        gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    platform:     linux/amd64
    stdin_open:   true
    tty:          true
    secrets:
      - gcloud_sa_key.json
    build:
      dockerfile: docker/base/Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcloud_sa_key.json
    env_file:
      - ./hcloud/.env.dev
    volumes:
      - ./conf:/conf:ro
      - ./modules:/modules:rw
      - ./hcloud:/hcloud:rw
