---
# aaheiev/minecraft-iac:0.0.1-1
secrets:
  gcloud_sa_key.json:
    file: .secrets/bijlmerdreef-733-f730bf6b9a56.json
services:
  iac:
    image:        aaheiev/minecraft-iac:0.0.1-1
    platform:     linux/amd64
    stdin_open:   true
    tty:          true
    secrets:
      - gcloud_sa_key.json
    build:
      dockerfile: docker/base/Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcloud_sa_key.json
    env_file:
      - ./hcloud/.env.dev
    volumes:
      - ./ansible:/ansible:rw
      - ./conf:/conf:ro
      - ./modules:/modules:rw
      - ./hcloud:/hcloud:rw
