---
# tasks file for magento
- name: "create magent sowtware owner"
  user:
    name:    "{{ magento_os_user }}"
    comment: Magento Owner
    shell:   /bin/bash
    group:   www-data

- name: "install php composer"
  include_tasks: composer.yml

- name: "get magento"
  include_tasks: get_magento.yml

- name: "magento nginx config"
  notify: restart nginx
  template:
    src:   "nginx.conf.j2"
    dest:  "/etc/nginx/sites-available/{{ magento_name }}.conf"

- name: "enable magento nginx site"
  notify: restart nginx
  file:
    src:   "/etc/nginx/sites-available/{{ magento_name }}.conf"
    dest:  "/etc/nginx/sites-enabled/{{ magento_name }}"
    state: link

#- name: "change permissions to magento root"
#  command: chown -R www-data:www-data {{ magento_root }}
#  changed_when: false

- name: Attempt to change ownership on directory
  file:
    path: "{{ magento_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
