---
# defaults file for php
php_fpm:                   True
magento_run_mode:          default
php_version:
php_fpm_ini:               []
php_modules:               []
php_fpm_default_upstgream: "php-fpm"
php_fpm_default_pool_cfg:
  - { option: 'user',                    value: "www-data" }
  - { option: 'group',                   value: "www-data" }
  - { option: 'listen.owner',            value: "www-data" }
  - { option: 'listen.group',            value: "www-data" }
  - { option: 'pm',                      value: "dynamic" }
  - { option: 'pm.max_children',         value: "{{ ansible_processor_vcpus * 16 }}" }
  - { option: 'pm.start_servers',        value: "{{ ansible_processor_vcpus * 4 }}" }
  - { option: 'pm.min_spare_servers',    value: "{{ ansible_processor_vcpus * 1 }}" }
  - { option: 'pm.max_spare_servers',    value: "{{ ansible_processor_vcpus * 8 }}" }
  - { option: 'pm.max_requests',         value: "500" }
  - { option: 'pm.process_idle_timeout', value: "10s" }
