---
location: fsn1

ssh_key:
  name: deploy-ssh-key
  file_path: ~/.ssh/id_rsa.pub

minecraft:
  server:
    name: minecraft-server
    type: cpx31
    os: ubuntu-22.04
  storage:
    data_volume_name: minecraft-data
    data_volume_size_gb: 10
    data_volume_delete_protection: true
