---
# defaults file for percona
# repo settings and percona version
percona_server:         False
percona_release:        1.0-25
percona_version:        '5.7'
mysql_server_root_pass: change_it_t0_s0me_new_$0ne
mysqld_config_max_connections: 50
mysqld_pam_limits:
  - limit_type: soft
    limit_item: nofile
    value:      "1024"
  - limit_type: hard
    limit_item: nofile
    value:      "65536"
  - limit_type: soft
    limit_item: nproc
    value:      "16384"
  - limit_type: hard
    limit_item: nproc
    value:      "16384"
  - limit_type: soft
    limit_item: stack
    value:      "10240"
  - limit_type: hard
    limit_item: stack
    value:      "32768"
mysqld_sysctl:
  - name:  fs.file-max
    value: "6815744"
  - name:  fs.aio-max-nr
    value: "1048576"
  - name:  vm.swappiness
    value: "10"
  - name:  vm.vfs_cache_pressure
    value: "200"
  - name:  net.ipv4.ip_local_port_range
    value: "9000 65535"
  - name:  kernel.sem
    value: "250 32000 100 128"
  - name:  kernel.shmmni
    value: "4096"
  - name:  kernel.shmall
    value: "1073741824"
  - name:  kernel.shmmax
    value: "4398046511104"
  - name:  kernel.panic_on_oops
    value: "1"
  - name:  net.core.rmem_default
    value: "262144"
  - name:  net.core.rmem_max
    value: "4194304"
  - name:  net.core.wmem_default
    value: "262144"
  - name:  net.core.wmem_max
    value: "1048576"
  - name:  net.ipv4.conf.all.rp_filter
    value: "2"
  - name:  net.ipv4.conf.default.rp_filter
    value: "2"

mysqld_config_common:
  - { option: 'max_connections',                 value: "{{ mysqld_config_max_connections }}" }
  - { option: 'skip-external-locking',           value: "1" }
  - { option: 'skip-name-resolve',               value: "1" }
  - { option: 'default_storage_engine',          value: "InnoDB" }
  - { option: 'explicit_defaults_for_timestamp', value: 1 }
  - { option: 'symbolic-links',                  value: 0 }
  - { option: 'bind-address',                    value: '0.0.0.0' }
  - { option: 'open_files_limit',                value: 131242 }
  - { option: 'local-infile',                    value: 0 }
  - { option: 'max_allowed_packet',              value: "64M" }

mysqld_config:
  - { option: 'key_buffer_size',                 value: "8M" }
  - { option: 'join_buffer_size',                value: "4MB"}
  - { option: 'tmp_table_size',                  value: "1M" }
  - { option: 'max-heap-table-size',             value: "512M" }
  - { option: 'table-open-cache',                value: 131242 }
  - { option: 'table_definition_cache',          value: 4096 }
  - { option: 'query_cache_type',                value: "OFF" }
  - { option: 'query_cache_size',                value: 0 }
  - { option: 'thread_stack',                    value: '192K' }
  - { option: 'thread_pool_size',                value: 24 }
  - { option: 'thread_cache_size',               value: 256 }
  - { option: 'sort-buffer-size',                value: '16M' }

mysqld_config_logs:
  - { option: 'log_warnings',                    value: "3" }
  - { option: 'log_error',                       value: '/var/log/mysql/error.log' }
  - { option: 'general_log_file',                value: '/var/log/mysql/general.log' }
  - { option: 'general_log',                     value: "0" }
  - { option: 'slow_query_log_file',             value: '/var/log/mysql/slow_query.log' }
  - { option: 'slow_query_log',                  value: "0" }
  - { option: 'long_query_time',                 value: "5" }
  - { option: 'log_queries_not_using_indexes',   value: "1" }

mysqld_config_innodb_common:
  - { option: 'innodb_file_per_table',           value: 1 }
  - { option: 'innodb_flush_method',             value: 'O_DIRECT' }
  - { option: 'innodb_table_locks',              value: 0 }
  - { option: 'innodb_flush_log_at_trx_commit',  value: 1 }
  - { option: 'innodb_lock_wait_timeout',        value: 120 }
  - { option: 'innodb_max_dirty_pages_pct',      value: 90 }
  - { option: 'innodb_thread_concurrency',       value: 0 }
  - { option: 'ft_min_word_len',                 value: 2 }
  - { option: 'innodb_buffer_pool_instances',    value: "{{ ansible_processor_vcpus }}" }
  - { option: 'innodb_buffer_pool_size',         value: "{{ ansible_processor_vcpus }}G" }

#  - { option: 'read_buffer_size',               value: "{{ (ansible_memtotal_mb/10)|round|int }}MB" } # 1/4 OF ALL RAM
#  - { option: 'read_rnd_buffer_size',           value: "{{ (ansible_memtotal_mb/8)|round|int }}MB" }  # 1/8 of RAM

mysqld_config_innodb:
  - { option: 'innodb_buffer_pool_chunk_size',   value: 256M }
#  - { option: 'innodb_log_files_in_group',      value: 2 }
#  - { option: 'innodb_log_file_size',           value: "{{ (ansible_memtotal_mb/8)|round|int }}MB" }  # 1/8 of RAM
#  - { option: 'innodb_log_buffer_size',         value: 64M }

mysqld_config_replication:
  - { option: 'server-id',                       value: 1 }
  - { option: 'log-bin',                         value: "mysql-bin" }
  - { option: 'relay-log',                       value: "relay-bin" }
  - { option: 'binlog_format',                   value: "row" }
  - { option: 'max_binlog_files',                value: 30 }
  - { option: 'max_binlog_size',                 value: "250M" }
  - { option: 'expire_logs_days',                value: 30 }
