---
###############################################################################
# install php-fpm
###############################################################################
- name: "install php-fpm"
  apt: name="{{ php_version }}-fpm"

###############################################################################
# configure php-fpm/php.ini
###############################################################################
- name: "configure global php-fpm"
  notify: restart php-fpm
  ini_file:
    dest:     "{{ php_config_dir }}/fpm/php.ini"
    section:  "{{ item.section }}"
    option:   "{{ item.option }}"
    value:    "{{ item.value }}"
  with_items: "{{ php_fpm_ini }}"
  when: php_fpm_ini.0 is defined

###############################################################################
# configure FPM default pool www
###############################################################################
- name: "configure default php-fpm pool [www] with static options"
  notify: restart php-fpm
  ini_file:
    path:    "{{ php_config_dir }}/fpm/pool.d/www.conf"
    section: www
    option:  "{{ item.option }}"
    value:   "{{ item.value }}"
  with_items:
    - { option: 'listen', value: "{{ php_fpm_sock_path }}" }

- name: "configure default php-fpm pool [www] with configured options"
  notify: restart php-fpm
  ini_file:
    path:    "{{ php_config_dir }}/fpm/pool.d/www.conf"
    section: www
    option:   "{{ item.option }}"
    value:    "{{ item.value }}"
  with_items: "{{ php_fpm_default_pool_cfg }}"

- name: "configure default php-fpm pool [www] environment variables"
  notify: restart php-fpm
  ini_file:
    path:    "{{ php_config_dir }}/fpm/pool.d/www.conf"
    section: www
    option:   "{{ item.option }}"
    value:    "{{ item.value }}"
  with_items:
    - { option: 'env[MAGE_MODE]', value: "{{ magento_run_mode }}" }

###############################################################################
# configure nginx upstream to $php_fpm_sock_path
###############################################################################
- name: "check nginx conf.d directory exists"
  stat: path=/etc/nginx/conf.d
  register: nginx_conf_d_dir

- name: 'nginx upstream for php-fpm pool'
  notify: restart nginx
  template:
    src:  nginx-upstream.conf.j2
    dest: '/etc/nginx/conf.d/php-fpm.conf'
    mode: 0644
  when: nginx_conf_d_dir.stat.isdir is defined and nginx_conf_d_dir.stat.isdir
