---
- name:           add duplicity ppa
  apt_repository: repo=ppa:duplicity-team/duplicity-release-git update_cache=yes
- name:           install packages
  package:
    state:        latest
    name:
      - awscli
      - duplicity
      - python3-boto
      - python3-boto3
      - python3-botocore
      - python3-pip

