---
# tasks file for duplicity
- name:   update alternatives for python
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name:   install duplicity on ubuntu
  include_tasks: install-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"

- name: install s3cmd
  import_tasks: s3cmd.yml

- name: configure aws-cli
  import_tasks: awscli.yml

- name: install duplicity-backup.sh script
  get_url:
    url:  https://raw.githubusercontent.com/zertrin/duplicity-backup.sh/dev/duplicity-backup.sh
    dest: /usr/local/bin/duplicity-backup.sh
    mode: 0755
