---
- name:         install s3cmd
  pip:
    name:
      - s3cmd
      - boto
    executable: pip3

- name:         set s3cmd config path
  set_fact:
    s3cmd_config_path: "{{ ansible_env.HOME }}/.s3cfg"

- name:         configure s3cmd
  no_log:       True
  ini_file:
    path:       "{{ ansible_env.HOME }}/.s3cfg"
    section:    default
    mode:       0644
    option:     "{{ item.option }}"
    value:      "{{ item.value }}"
  with_items:
    - option:   bucket_location
      value:    "{{ duplicity_aws_region }}"
    - option:   access_key
      value:    "{{ duplicity_aws_access_key_id }}"
    - option:   secret_key
      value:    "{{ duplicity_aws_secret_access_key }}"
